Fix build action

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -93,11 +93,7 @@ jobs:
       run: make pre-ui
 
     - name: Generate
-      # Make sure generate does not need to be run
-      run: |
-        make generate
-        git add --intent-to-add .
-        git diff --stat --exit-code
+      run: make generate
 
     - name: Build UI
       # skip UI build for pull requests if UI is unchanged (UI was cached)
@@ -110,6 +106,14 @@ jobs:
       env:
         POSTGRES_DB: postgres:postgres@localhost/postgres?sslmode=disable
       run: make it
+
+    - name: Check generated files
+      run: |
+        if ! git diff --exit-code; then
+          echo "::error::Generated files have changed. Run 'make generate' locally and commit the changes."
+          git diff
+          exit 1
+        fi
 
     - name: Set PR version
       if: ${{ github.event_name == 'pull_request' && github.base_ref != 'refs/heads/master'}}
